name: Tailwind CSS Build and Deploy

on:
  push:
    branches:
      - main  
    paths:
      - "themes/**"  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: | 
            cd ./themes/insight
             npm install

      - name: Install Tailwind CSS
        run: |
            cd ./themes/insight
            npm install -g tailwindcss

      - name: Compile Tailwind CSS
        run: |
            cd ./themes/insight 
            npx tailwindcss -i ./assets/src/input.css -o ./assets/dist/output.css --minify

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Upload Compiled CSS via SFTP
        env:
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASS: ${{ secrets.SFTP_PASS }}
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_PORT: ${{ secrets.SFTP_PORT || 22 }}
          SFTP_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}
        run: |
          set -e  # Exit on error
          echo "Uploading compiled Tailwind CSS..."
          
          # Set up SSH Key for authentication
          mkdir -p ~/.ssh
          echo "$SFTP_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p $SFTP_PORT $SFTP_USER@$SFTP_HOST "echo 'SSH connection successful'"

          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p $SFTP_PORT" \
            ./themes/insight/ \
            $SFTP_USER@$SFTP_HOST:/home/755960.cloudwaysapps.com/xgpkqbhmap/public_html/wp-content/themes/insight/

          echo "Upload completed successfully!"
